name: Build CLI Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build CLI for multiple platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: darwin
            goarch: arm64
            output: tome-darwin-arm-osx-m1
          - goos: linux
            goarch: amd64
            output: tome-linux-amd64
          - goos: windows
            goarch: amd64
            output: tome-win.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o ${{ matrix.output }} ./protocol/v1/librarian/cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}

  release:
    name: Create release with binaries
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: binaries/

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}